#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=CheckEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:10:00
#SBATCH --output=/home/scur0695/logs/out-%x.%A.out
#SBATCH --error=/home/scur0695/logs/err-%x.%A.err

module purge
module load 2023
module load Anaconda3/2023.07-2

module load 2022
module load Python/3.10.4-GCCcore-11.3.0
module load CUDA/11.7.0

# Activate your environment
source activate gaussian_grouping
# Check whether the GPU is available
python -uc "import torch; print('\n\nGPU available?', torch.cuda.is_available())"