#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=Sam2Env
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=1:00:00
#SBATCH --output=/home/scur0695/logs/out-%x.%A.out
#SBATCH --error=/home/scur0695/logs/err-%x.%A.err

module load 2022
module load Python/3.10.4-GCCcore-11.3.0
module load CUDA/11.8.0
module load Anaconda3/2022.05

# conda create -n sam2
source activate sam2

# conda install pytorch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1  pytorch-cuda=11.8 -c pytorch -c nvidia
# conda install pip

echo "move to sam and install e"
cd sam2/
pip install -e .

echo "Done"

