#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=01:00:00
#SBATCH --output=/home/scur0680/logs/out-%x.%A.out
#SBATCH --error=/home/scur0680/logs/err-%x.%A.err

# module purge
# # The default modules for deep learning
# module load 2023
# module load Anaconda3/2023.07-2
module load 2022
module load Python/3.10.4-GCCcore-11.3.0
module load CUDA/11.7.0
module load Anaconda3/2022.05

# Go to the directory that contains the conda env file and install it
cd $HOME/CV2_Project/gaussian-grouping
conda create -n gaussian_grouping python=3.8 -y
source activate gaussian_grouping 

conda install pytorch==1.13.0 torchvision==0.14.0 torchaudio==0.13.0 pytorch-cuda=11.7 -c pytorch -c nvidia
conda install pip
pip install plyfile==0.8.1
pip install tqdm scipy wandb opencv-python scikit-learn lpips

pip install submodules/diff-gaussian-rasterization
pip install submodules/simple-knn