#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=TrainReplica
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=20:00:00
#SBATCH --output=/home/scur0695/logs/out-%x.%A.out
#SBATCH --error=/home/scur0695/logs/err-%x.%A.err

module load 2022
module load Python/3.10.4-GCCcore-11.3.0
module load CUDA/11.7.0

cd gaussian-grouping
source env/bin/activate

datasets=("office0" "office1" "office2" "room0" "room1" "scannet1_down" "scannet2_down" "scannet3_down" "scannet4_down" "scannet5_down")

for dataset in "${datasets[@]}"; do

    bash script/train.sh $dataset 1 # trains and renders the model
    

done
