#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=GSam2Demo
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=1:00:00
#SBATCH --output=/home/scur0695/logs/out-%x.%A.out
#SBATCH --error=/home/scur0695/logs/err-%x.%A.err

module load 2023 # required to load cuda12.1
module load Python/3.11.3-GCCcore-12.3.0
module load CUDA/12.1.1 # grounded sam2 requirement
module load Anaconda3/2023.07-2

source activate gsam2
cd Grounded-SAM-2


srun python grounded_sam2_tracking_demo.py