#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=SegformerOffice
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=02:00:00
#SBATCH --output=/home/scur0680/logs/out-%x.%A.out
#SBATCH --error=/home/scur0680/logs/err-%x.%A.err

module load 2022
module load Python/3.10.4-GCCcore-11.3.0
module load CUDA/11.7.0
module load Anaconda3/2022.05

cd $HOME/CV2_Project
source activate gaussian_grouping
# pip install -U openmim
# mim install mmengine
# mim install "mmcv==2.0.0"
# pip install "mmsegmentation>=1.0.0"

# pip install ftfy
# pip install regex

srun python segformer_masks.py