#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=TrainReplica
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=20:00:00
#SBATCH --output=/home/scur0695/logs/out-%x.%A.out
#SBATCH --error=/home/scur0695/logs/err-%x.%A.err

module load 2022
module load Python/3.10.4-GCCcore-11.3.0
module load CUDA/11.7.0

cd gaussian-grouping
source env/bin/activate

# bash script/train.sh office0 1
bash script/train.sh office1 1
# bash script/train.sh office2 1
bash script/train.sh room0 1
bash script/train.sh room1 1