#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=04:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2022
module load CUDA/11.7.0
#module load Anaconda3/2023.07-2


source ~/miniconda3/etc/profile.d/conda.sh
#conda init
conda activate gaussian_grouping

# Run your script with args
cd $HOME/gaussian-grouping
bash script/train.sh bear 1
